name: hydra-demo
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - icu=78.2
  - libexpat=2.7.3
  - libffi=3.5.2
  - liblzma=5.8.2
  - libmpdec=4.0.0
  - libsqlite=3.51.2
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.1
  - pip=26.0.1
  - python=3.13.12
  - python_abi=3.13
  - readline=8.3
  - tk=8.6.13
  - tzdata=2025c
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/hydra-demo
