[project]
name = "hydra-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.3.1",
    "feature-engine>=1.9.3",
    "hydra-core>=1.3.2",
    "polars>=1.38.1",
    "scikit-learn>=1.8.0",
]
